name: Sync new crew
on: workflow_dispatch
jobs:
  # Checkout all repos
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          repository: stt-datacore/website
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: website

      - name: Checkout scripts
        uses: actions/checkout@v2
        with:
          repository: stt-datacore/scripts
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: scripts

      - name: Checkout zhatvash
        uses: actions/checkout@v2
        with:
          repository: ineffyble/zhatvash
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: scripts/zhatvash

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
  # Scripts specific tasks, run one after each other after checkout
  install-scripts:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: NPM install
        run: npm ci
        working-directory: scripts
  run-parseallcrew-script:
    needs: install-scripts
    runs-on: ubuntu-latest
    steps:
      - name: Run parseallcrew.js
        run: node parseallcrew.js
        working-directory: scripts
  # Website set up, runs in parallel with scripts tasks
  install-website:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: NPM install
        run: npm ci
        working-directory: website
  # Website precalculate, runs after scripts tasks if crew change detected
  # Commit all changes to respective repos and push